services:
  redis:
    image: "redis:3.2"
    volumes:
      - "/var/docker/data/redis:/data"

  web:
    build: .
    command: bundle exec thin -R config.ru -a '0.0.0.0' -p 9292 start
    ports:
      - "9292:9292"
    environment:
      - RACK_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    links:
      - redis
